name: 'JS Monorepo Deploy Nightly'
description: 'Deploys packages/* npm/vscode packages when the change'
author: 'Orta Therox'
inputs:
  since:
    description: 'The time between deploys'
    default: '1 day'
  cwd:
    description: 'The path to the folder which hosts packages'
    default: '.'
  install:
    description: 'Run npm install before deploying a package, defaults to off'
    default: 'false'
  sort:
    description: 'The sort order for the deploy process based on the names of the packages, expected to be a JSON.parse-able array of string.'
runs:
  using: 'node12'
  main: 'dist/index.js'
