name: 'JS Monorepo Deploy Nightly'
description: 'Deploys packages/* for npm/vscode packages when they change'
author: 'Orta Therox'
inputs:
  since:
    description: 'The time between deploys'
    default: '1 day'
  cwd:
    description: 'The path to the folder which hosts packages'
    default: '.'
  install:
    description: 'Run npm install before deploying a package, defaults to off'
    default: 'false'
  sort:
    description: 'The sort order for the deploy process based on the names of the packages, expected to be a JSON.parse-able array of string.'
  only:
    description: 'If you only want to deploy specific packages, list them here.'
  vsce-params:
    default: ''
    description: 'Additional params for the vsce command'
runs:
  using: 'node12'
  main: 'dist/index.js'
